name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  go_router: ^6.5.0
  lottie: ^3.3.2
  fl_chart: ^1.1.1
  google_fonts: ^5.0.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/onboarding1.json
    - assets/lottie/onboarding2.json
    - assets/lottie/onboarding3.json
    - assets/images/
