name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  go_router: ^6.5.0
  lottie: ^3.3.2
  fl_chart: ^1.1.1
  google_fonts: ^5.0.0
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  # API & Network
  dio: ^5.4.0
  http: ^1.2.0
  http_parser: ^4.0.2
  json_annotation: ^4.8.1
  # Utilities
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/onboarding1.json
    - assets/lottie/onboarding2.json
    - assets/lottie/onboarding3.json
    - assets/images/
