services:
  postgres_test:
    image: postgres:16
    container_name: test_backend_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: creditxai_test
    ports:
      - "5433:5432"
    networks:
      - creditxai_test_net

  minio_test:
    image: quay.io/minio/minio
    container_name: test_backend_storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - minio_test_data:/data
    networks:
      - creditxai_test_net

networks:
  creditxai_test_net:
    driver: bridge

volumes:
  minio_test_data:
